### ISSUE TITLE
Radius is significantly greater than other tools

### ISSUE THREAD

**Issue by beardedsamwise** [jmargenberg/covid-5km-overlap-finder#2]
Compared to The Age and Government tools your radius is way bigger, are you sure it's calculated correctly? 

https://www.theage.com.au/national/victoria/interactive-see-where-your-5km-lockdown-limit-ends-20200801-p55hns.html

https://www.vic.gov.au/coronavirus-5km-from-home-map

<img width="1055" alt="Screen Shot 2020-09-23 at 12 22 32 pm" src="https://user-images.githubusercontent.com/22190221/93957384-87e45a80-fd97-11ea-98fa-8e3caa6ca5f7.png">
<img width="938" alt="Screen Shot 2020-09-23 at 12 22 21 pm" src="https://user-images.githubusercontent.com/22190221/93957411-8f0b6880-fd97-11ea-9e6a-158336d4339e.png">
<img width="1291" alt="Screen Shot 2020-09-23 at 12 22 40 pm" src="https://user-images.githubusercontent.com/22190221/93957370-8024b600-fd97-11ea-9b6f-9f8f556d142f.png">

**Comment by jmargenberg** [comment]
@beardedsamwise could you please let me know which test address you were using to compare the radius drawn by each site?

I just did a comparison using the corner of Elizabeth and Bourke street and the lockdown areas seems to be virtually identical between each site.
VicGov site:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/34509336/94139056-6032e680-feac-11ea-8c8a-520bfbbccb68.png">

The Age:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/34509336/94139102-72148980-feac-11ea-86dc-4d86661b184f.png">

Covid 5km Overlap Finder
<img width="726" alt="image" src="https://user-images.githubusercontent.com/34509336/94139217-9e300a80-feac-11ea-9ec3-a4bb08f9ed58.png">

I also performed numerous manual checks before publishing to verify that the lockdown areas were in fact the correct size.

It could be that the search provider I'm using returns a different latlong for the same address search, leading to this site drawing the with a different center.

The other likely cause could be a rendering issue with mapbox. I can't replicate this but I just double checked the code that I use to generate the lockdown areas and it is pretty straightforward with no obvious errors.:
``` typescript
const COVID_LOCKDOWN_RADIUS_KM = 5;
const COVID_LOCKDOWN_CIRCLE_OPTIONS = { steps: 1_000, units: "kilometers" };
 
...

// Determine each users total lockdown area
const myLockdownArea = myLocation && turf.circle(myLocation, COVID_LOCKDOWN_RADIUS_KM, COVID_LOCKDOWN_CIRCLE_OPTIONS);
const theirLockdownArea =
    theirLocation && turf.circle(theirLocation, COVID_LOCKDOWN_RADIUS_KM, COVID_LOCKDOWN_CIRCLE_OPTIONS);

...

// Determine each users exclusive lockdown area (their entire lockdown area if only one provided)
  const myExclusiveLockdownArea = bothLocationsSet
    ? turf.difference(myLockdownArea, theirLockdownArea)
    : myLockdownArea;
  const theirExclusiveLockdownArea = bothLocationsSet
    ? turf.difference(theirLockdownArea, myLockdownArea)
    : theirLockdownArea;
...

     <GeoJSONLayer
        data={turf.featureCollection([myExclusiveLockdownArea].filter(notFalsy))}
        linePaint={MAP_BOX_STYLES.myExclusiveAreaLinePaint}
        fillPaint={MAP_BOX_STYLES.myExclusiveAreaFillPaint}
      ></GeoJSONLayer>
      <GeoJSONLayer
        data={turf.featureCollection([theirExclusiveLockdownArea].filter(notFalsy))}
        linePaint={MAP_BOX_STYLES.theirExclusiveAreaLinePaint}
        fillPaint={MAP_BOX_STYLES.theirExclusiveAreaFillPaint}
      ></GeoJSONLayer>

```

**Comment by beardedsamwise** [comment]
Not really keen to post my address publicly, can you send me your socials and I'll DM you.

**Comment by jmargenberg** [comment]
Of course, I completely understand. You can dm me on twitter (@JMargenberg), LinkedIn (https://www.linkedin.com/in/james-margenberg/) or email me at covid.5km.overlap.finder@gmail.com. Thanks in advance.

**Comment by jmargenberg** [comment]
I received the test address from @beardedsamwise and determined that the issue was due to my adress search provider giving inaccurate coordinates for the particular address. I am going to close this issue and create a separate PR to introduce a marker in the center of each lockdown radius so that users can easily see if the coordinates being used are inaccurate.
