### ISSUE TITLE
Some addresses are incorrect

### ISSUE THREAD

**Issue by michaelblight** [jmargenberg/covid-5km-overlap-finder#3]
For example

- 5 Olive St Malvern East shows as being somewhere in Caulfield, several km away
- 5 Egan St Richmond doesn't show up in the predictive text, Springvale does. However pressing enter shows the text of Springvale, but shows the radius for Richmond
- 5 Hilda St Malvern East doesn't show up in the predictive text, Tarneit does. Pressing enter shows the text of Tarneit, but the radius is somewhere in Mooney Ponds, about 30km away.

**Comment by iClick-Oz** [comment]
Great site. Came here to offer same feedback. Robinson Rd Hawthorn isn't recognised. I checked with Open Maps and it is okay at there.

**Comment by jmargenberg** [comment]
Apologies for the absurdly slow reply but thank you for reporting this @michaelblight and @iClick-Oz!

I am and was aware of this as an issue/limitation of the address search provider which I had to switch to. I was originally using Google Places which wouldn't have had these issues but was unfortunately costing several hundred dollars a day whilst this webapp was experiencing it's peak traffic last year 😬.

My current search provider (Algolia) is lower quality and is missing a lot of street addresses but is an order of magnitude cheaper allowing me to keep this site online 😄

**Comment by michaelblight** [comment]
Welcome to the new world we live in. Who would have wanted this type of query to go viral. Well done on the site.
