### ISSUE TITLE
10 Station street, Caulfield north, Victoria isn't in Caulfield North

### ISSUE THREAD

**Issue by SuryaOTL** [jmargenberg/covid-5km-overlap-finder#4]
It's showing somewhere in the west side for some reason.

**Comment by jmargenberg** [comment]
Thanks for reporting this @SuryaOTL! I can see that this address is in-fact reporting the wrong location bizarrely.

Unfortunately this looks like an issue/limitation of the address search provider I'm using at the moment. I was originally using Google Places which wouldn't have this issue but was unfortunately costing several hundred dollars a day whilst this webapp was experiencing it's peak traffic last year 😬.

My current search provider (Algolia) is lower quality and leads to these kind of dodgy search results but is an order of magnitude cheaper allowing me to keep this site online 😄
