### ISSUE TITLE
Address finder only finds one address

### ISSUE THREAD

**Issue by jod999** [jmargenberg/covid-5km-overlap-finder#6]
Thanks for your lockdown overlap finder. It is great. 

Just one quibble: 

- When I type in my address (e.g. 53 Argyle Street, St Kilda, 3182) in either address box, the system will only find 53 Argyle Street, Reservoir, Victoria. There are several Argyle Streets in Victoria, but I can only choose one. 

For your diagnostic info, I found this issue at about 24 September 2021 on Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit), running on Windows 10 Education version 1809. 

I see the same issue on:

- Chrome (which isn't surprising, given that Brave is a Chrome skin). 
- Firefox
- Edge. 

Have you constrained the suggestion field to only show one suggestion? Normally when I type an address (e.g. Google Maps, Australia Post) I get a number of Argyle Street suggestions, and choose the St Kilda one. Your page doesn't do that. 

Happy to help with more information or for testing purposes. I can be contacted at 0425 755 829. 

Jonathan

**Comment by jmargenberg** [comment]
Hi Jonathon, thank you for raising this issue and providing such detailed details for me to debug.

Unfortunately this looks like an issue/limitation of the address search provider I'm using at the moment. I was originally using Google Places which would have almost certainly would have worked for this search but was costing several hundred dollars a day whilst this webapp was experiencing it's peak traffic last year 😬.

My current search provider (Algolia) is unfortunately lower quality and leads to these kind of dodgy search results but is an order of magnitude cheaper allowing me to keep this site online 😄
